development:
  tomorrow_job:
    class: TomorrowJob
    queue: background
    schedule: at midnight every day

production:
  tomorrow_job:
    class: TomorrowJob
    queue: background
    schedule: at midnight every day

#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
